---
# Source: my-nginx-chart/templates/deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx Custom Page</title>
    </head>
    <body>
      <p>V7</p>
    </body>
    </html>
---
# Source: my-nginx-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-nginx
---
# Source: my-nginx-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: my-nginx-config
