apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
spec:
  project: default
  source:
    path: ''
    repoURL: 'https://helm.github.io/examples'
    targetRevision: 0.1.0
    chart: hello-worldz
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
