apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jin
spec:
  project: default
  source:
    path: ''
    repoURL: 'https://helm.github.io/examples'
    targetRevision: 0.1.0
    chart: hello-world
  destination:
    namespace: argocd
  syncPolicy:
    automated: {}